name: Code Check

on:
  # Runs on pull requests.
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  # This event will only trigger a workflow run if the workflow file is on the default branch.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
